<template>
  <div class="flex flex-col justify-center text-center mx-4">
    <h1 class="text-3xl mb-5">{{ service }}</h1>
    <p class="text-left text-gray-300">{{ serviceText }}</p>
  </div>
</template>
<script>
export default {
  data() {
    return {
      serviceText: String,
    };
  },
  props: {
    // title: String,
    service: String,
  },
  mounted() {
    switch (this.service) {
      case "Vandkraftinvestering i Grønland":
        this.serviceText =
          "Folkene bag GreenLead har igennem de sidste 5 år arbejdet med at realisere vandkraftinvesteringer i Grønland. Det er i den tid blevet til vedtagelsen af 4 vandkraftværker i det grønlandsk parlament fra 0,2MW til 55 MW i effektstørrelse - en anlægspakke på ca. 3,1 mia. DKK. I Grønland er der katalogiseret 66 forskellige vandkraftpotentialer på den grønlandske vestkyst, med hydrologiske data tilbage fra 70'erne. Vi har et stort kendskab til disse potentialer, samt de mange forhold som man bør gøre sig bekendt med i forhold til geografi og geologi, gletcherpåvirkning, søkabler og transmission, befolkningsnærhed, afsætningsmuligheder, lokale kompetencer til drift og sideindustri, og meget mere. ​ Yderlige har vi fra GreenLead stor kendskab til den politiske proces som ligger forud for undersøgelsestilladelser og udnyttelsestilladelser, samt hvordan dialogen omkring Impact Benefit Analysis (IBA) gribes an, så både Grønland og Investor opnår størst mulig sucess. Yderligere har vi drevet virksomhed og været borgere i Grønland i en lang årrække fra 2012 - 2021 hvorved vi har opnået stort kendskab til forretningsmiljøet, kulturen, lokale kontakter, logistik, issituationer, det grønlandske tærren og meget mere som er helt essensielt for at drive virksomhed i Grønland. ​ Vi kan hjælpe din virksomhed med at finde det rigtige vandkraftprojekt, designe en aftager af energien, og sikre økonomi og bæredygtighed i dit projekt. ​ Grønland er på mange måder som Klondike var i 1896 før the Gold rush - fyldt med fantastiske økonomiske muligheder. Grønland er blot ikke opdaget endnu på den store verdensscene.";
        break;
      case "Varmebatterier til procesanlæg og varmecentraler":
        this.serviceText =
          "Har din virksomhed behov for omstilling væk fra gas og olie, og over i en elektrisk løsning, så har vi mulighed for at hjælpe dig. Vi tilbyder turnkey løsninger, med ændringer af procesanlæg og varmecentraler som tilkobles et varmebatteri hvor hjertet består af magnesiumsten. Varme lagres i batterierne når strøm på nettet er billig - eller der indgås en lav fastprisaftale på off-peak tider som 01 - 05 om natten, og energien leveres efterfølgende tilbage resten af døgnet. Batteriet har en arbejdstemperatur op til 700 grader celcius, og kapaciteten er fra 0,5 MWh til 300 MWh, med en varmeeffekt fra 0,2 MW til 100 MW. Anlægget kan både dimensioneres til at overtage al varmelevering, eller fungere som et supplement til øvrige løsninger. Anlægget er ideelt for både procesvarme op til 700 grader, samt varmecentraler i virksomheder eller fjernvarmenet for forsyningsvirksomheder. ​ Effektiviteten med standardisolering er 95% tilbagelevering af energi, med et dagligt tab på omkring 1%. Ved større isolering kan tabet reduceres yderligere. ​ Rentabiliteten af anlæggene er ganske god, og oftest vil en kunde opleve en billigere energiløsning end gas eller oliebaseret energi. Forud for hvert projekt foretages en rentabilitetsanalyse, så man kender de økonomiske forudsætninger, samt hvilke priser på gas, olie og el, der ligger til grund for positiv retabilitet af anlægget. ​ GreenLead kan desuden være behjælpelig med leasingordninger på anlæggene, samt en service og vedligeholdelsesaftale med garanteret oppetid. ";
        break;
      case "Energirådgivning og optimering":
        this.serviceText =
          "Påtænker jeres virksomhed en ændring af jeres fodaftryk på klima- og energifronten? Er I list i tvivl om hvad der giver mest virkning ift. investering? Og tænker I at det kunne være godt med en investering i energioptimering som rent faktisk giver et afkast, så læs videre. ​ Hos GreenLead har vi arbejdet med grøn omstilling i ganske mange år, siden 2001. Også før det blev rigtig populært. Først inden for vindkraft, så vandkraft, samt sol, batterier, waste-to-energy, isolering af facader, med mere. Størrelsesmæssigt har vi arbejdet med anlæg på 30 kw op til 100 MW, og vi kan skalere højere op efter behov. ​ Den viden vil vi gerne bringe i spild overfor din virksomhed, så vi kan designe nogle helhedsløsninger, som undersøger alle teknologiernes relevans ift. jeres virksomhed og jeres behov, under hensynstagen til jeres elaftaler, gasaftaler, afgiftsforhold, med mere. Vi kan skabe helhedsløsninger sammen med jer, som både optimerer, omlægger, og sågar udvinder CO2 fra jeres eventuelle procesanlæg, så jeres klaima fodaftryk bliver så småt som det økonomisk er muligt eller endnu længere hvis ønsket. ​ Vi hjælper jer med teknisk analyse, økonomisk analyse, projektstyring, leverandørkontankt, opstilling, test, og efterfølgende virkningradsevalueringer. ";
        break;
      case "Forsyningsrådgivning":
        this.serviceText =
          "Med mange års erfaring med ledelse af Grønlands forsyningsselskab, samt hos danske waste-to-energy aktører, ønsker vi at hjælpe din forsyningsvirksomhed. ​ Vi har i GreenLead medarbejdere med forsyningserfaring som administrerende direktør, økonomidirektør, teknisk direktør, operationsdirektør, vedligeholdelseschef, samt med ansvar for chefer for regnskab, salg, kommunikation, IT, projektudførelse, vedligehold og drift, HR, kundeservice, udvikling, og alt derimellem. Vi har arbejdet med strategiudvikling i en forsyningskontekst, governancestrukturer, organisationsforandring, opsplitning af virksomheder, introduktion af ny teknologi, indførelse af nye IT-systemer, kundetilfredshedskampagner, ledelsesudviklingsprogrammer, medarbejdertilfredshedsworkshop, indførelse af kunstig intelligens i administrationsarbejdet, indførelse af softwarerobotter, og meget, meget mere. ​ Vi elsker forsyning og teknisk til el, vand og varme, samt de understøttende systemer. Vi håber vi må få lov til at bringe vores viden i spil i din forsyningsvirksomhed.";
        break;
      case "Nationale energisystemer":
        this.serviceText =
          "GreenLead tilbyder din forsyningssektoren hjælp til forretningsanalyser, med prissætning, tilslutningsvilkår, backupforpligtelser, standby omkostninger, spidsbelastningsafhjælpning, segmentopdeling af forbrugertyper, introduktion af ny teknologi i til forsyning og meget mere. ​ Vi har arbejdet med at lave nationale rammer for energiforsyning og energiplanlægning for hele Grønland. Et helt enormt land på størrelse med halvdelen af Europa og med relativt mange anlæg ift. befolkningsstørrelsen. Vi haft ansvaret for 91kraftværker, 23 varmeværker og 69 vandværker, samt 70 standalone el-distributionsnet og 23 fjernvarme-distributionsnet som vi har haft ansvaret for, som henholdsvis CEO, CFO og COO af hele Grønlands el- vand og varmeforsyning, Nukissiorfiit. Vi havde godt 400 ansatte som varetog opgaven under vores ledelse. ​ Vi har designet nationale prissystemer, nationale standardvilkår for forsyning for el, vand, og varme, tilslutningsbetingelser, anvist krav ift. backup, og meget mere. Vi har udarbejdet den nationale plan for at omstille Grønlands tilbageværende dieselelkraft til vedvarende energi, hvor vi har været idémagere og drivkraft for vedtagelsen en anlægslov- og finansieringspakke til 3,1 mia. Kr til opførelse af to nye store vandkraftværker. Vi har indført ny teknologi ind i forsyningsnetværket med hybridanlæg og energi-storage. Vi har arbejdet tæt sammen med ministerier og ministre i mange af den slags proceser med bekendtgørelser, lovpakker, salgsfremstød og krisehåndtering. Vi kender en del til arbejdet når man har de nationale briller på. Kvaliteter som vi håber kan hjælpe andre aktører inden for forsyningssektoren.";
        break;
      case "Projektudvikling til den grønne omstilling":
        this.serviceText =
          "I GreenLead har vi tilsammen årtiers erfaring med grøn omstilling, kæmpe energisystemer, og det politiske arbejde for at få projekter fra idé til virkelighed. Vi har i særdeleshed arbejdet med vandkraftværker i Arktis fra 0,25 MW til 50 MW til 1500 MW anlæg. Alle samme projekter i hver sin kategori. Vi har erfaring fra vindmøllebranchen med små nichemøller helt ned i husmandsbehov, op til store havvindmøller i 8-9 MW klassen. Vi har arbejdet med solcelleanlæg til forsyning af små øde samfund, til lidt større anlæg i regulære byer. Vi har arbejdet med batteriløsninger til netbalancering, til opbevaring af energi for natten, og til optimering af ICE GEN-set, så levetiden forlænges og miljø og pengepung spares for afbrænding af diesel. ​ I lang tid har vi arbejdet med projektudvikling til Power to X, E-Fuels, og sektorkobling med industrihubs, hvor energiproducent, og en række enegiintensive aftagere sammentænkes i forhold til deres respektive behov samt biprodukter. Vi har arbejdet med bysystemer til elektricificering af almindelige personbiler, og i nyere tid, den næste generation af elektricificering af transport, hvor tung transport som lastbiler, busser og entreprenørmaskiner også kommer med på den grønne omstilling. ​ Arbejdet med den slags emner bliver ofte politiske. Vores rejse har ført os ind i mange dialoger med ministre, departementchefer og afdelingschefer, borgmestrer, kommunaldirektører, fagkonsulenter, you name it-, i det offentlige system. Nøglen til succes er sammenspil, tålmodighed, øjne som kan se løsninger på hver en barriere. ​ Hvis du har et projekt med energi og bæredygtighed, så hjælper vi gerne med projektudvikling og økonomisk og teknisk analyse. Vi brænder for den grønne omstilling! Det giver mål og mening at arbejde for at vores samfund, byer og virksomheder bliver nul-emission, og vores natur bliver varetaget på en måde så vi med stolthed kan give den videre til vores børn.";
        break;
      default:
        this.serviceText =
          "I GreenLead har vi tilsammen årtiers erfaring med grøn omstilling, kæmpe energisystemer, og det politiske arbejde for at få projekter fra idé til virkelighed. Vi har i særdeleshed arbejdet med vandkraftværker i Arktis fra 0,25 MW til 50 MW til 1500 MW anlæg. Alle samme projekter i hver sin kategori. Vi har erfaring fra vindmøllebranchen med små nichemøller helt ned i husmandsbehov, op til store havvindmøller i 8-9 MW klassen. Vi har arbejdet med solcelleanlæg til forsyning af små øde samfund, til lidt større anlæg i regulære byer. Vi har arbejdet med batteriløsninger til netbalancering, til opbevaring af energi for natten, og til optimering af ICE GEN-set, så levetiden forlænges og miljø og pengepung spares for afbrænding af diesel. ​ I lang tid har vi arbejdet med projektudvikling til Power to X, E-Fuels, og sektorkobling med industrihubs, hvor energiproducent, og en række enegiintensive aftagere sammentænkes i forhold til deres respektive behov samt biprodukter. Vi har arbejdet med bysystemer til elektricificering af almindelige personbiler, og i nyere tid, den næste generation af elektricificering af transport, hvor tung transport som lastbiler, busser og entreprenørmaskiner også kommer med på den grønne omstilling. ​ Arbejdet med den slags emner bliver ofte politiske. Vores rejse har ført os ind i mange dialoger med ministre, departementchefer og afdelingschefer, borgmestrer, kommunaldirektører, fagkonsulenter, you name it-, i det offentlige system. Nøglen til succes er sammenspil, tålmodighed, øjne som kan se løsninger på hver en barriere. ​ Hvis du har et projekt med energi og bæredygtighed, så hjælper vi gerne med projektudvikling og økonomisk og teknisk analyse. Vi brænder for den grønne omstilling! Det giver mål og mening at arbejde for at vores samfund, byer og virksomheder bliver nul-emission, og vores natur bliver varetaget på en måde så vi med stolthed kan give den videre til vores børn. ";
        break;
    }
  },
};
</script>
<style lang=""></style>
